name: ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install and upgrade pip
      run: |
        python3 -m pip install --upgrade pip

    - name: Install poetry
      run: pip3 install poetry==1.4.0

    - name: Install dependencies using poetry
      run: poetry install

    - name: Test with Pytest
      run: |
        poetry run task test
